<?php

/**
 * Reusable Tailwind class groups for high-contrast accents (news cards, project grid, sidebar, etc.).
 * Keys: border, hover_*, read_more, donate, sidebar_*, project_card_body, gallery_*,
 *       sidebar_header, section_underline, accent_badge, media_card_hover (News & Media cards).
 * Use: $c = config('tailwind_theme.accent_schemes')[$loop->index % count(config('tailwind_theme.accent_schemes'))];
 */
return [
    'accent_schemes' => [
        [
            'border' => 'border-green-500',
            'hover_bg' => 'hover:bg-green-500',
            'hover_border' => 'hover:border-green-50',
            'title_hover' => 'hover:text-green-600',
            'read_more' => 'text-green-600 border-green-600 hover:bg-green-600 hover:text-white group-hover:text-white group-hover:border-white group-hover:bg-transparent',
            'donate' => 'bg-green-600 hover:bg-green-700',
            'sidebar_row' => 'hover:bg-green-50 border-gray-200 hover:border-green-300',
            'sidebar_title' => 'group-hover:text-green-600',
            'sidebar_link' => 'text-green-600 group-hover:text-green-700',
            'project_card_body' => 'group-hover:bg-green-500',
            'gallery_image_border' => 'border-green-300',
            'gallery_view_link' => 'text-green-600 hover:text-green-800',
            'sidebar_header' => 'bg-green-800',
            'section_underline' => 'bg-green-600',
            'accent_badge' => 'bg-green-600',
            'media_card_hover' => 'border-2 border-gray-100 hover:border-green-400',
        ],
        [
            'border' => 'border-blue-500',
            'hover_bg' => 'hover:bg-blue-500',
            'hover_border' => 'hover:border-blue-50',
            'title_hover' => 'hover:text-blue-600',
            'read_more' => 'text-blue-600 border-blue-600 hover:bg-blue-600 hover:text-white group-hover:text-white group-hover:border-white group-hover:bg-transparent',
            'donate' => 'bg-blue-600 hover:bg-blue-700',
            'sidebar_row' => 'hover:bg-blue-50 border-gray-200 hover:border-blue-300',
            'sidebar_title' => 'group-hover:text-blue-600',
            'sidebar_link' => 'text-blue-600 group-hover:text-blue-700',
            'project_card_body' => 'group-hover:bg-blue-500',
            'gallery_image_border' => 'border-blue-300',
            'gallery_view_link' => 'text-blue-600 hover:text-blue-800',
            'sidebar_header' => 'bg-blue-800',
            'section_underline' => 'bg-blue-600',
            'accent_badge' => 'bg-blue-600',
            'media_card_hover' => 'border-2 border-gray-100 hover:border-blue-400',
        ],
        [
            'border' => 'border-red-500',
            'hover_bg' => 'hover:bg-red-500',
            'hover_border' => 'hover:border-red-50',
            'title_hover' => 'hover:text-red-600',
            'read_more' => 'text-red-600 border-red-600 hover:bg-red-600 hover:text-white group-hover:text-white group-hover:border-white group-hover:bg-transparent',
            'donate' => 'bg-red-600 hover:bg-red-700',
            'sidebar_row' => 'hover:bg-red-50 border-gray-200 hover:border-red-300',
            'sidebar_title' => 'group-hover:text-red-600',
            'sidebar_link' => 'text-red-600 group-hover:text-red-700',
            'project_card_body' => 'group-hover:bg-red-500',
            'gallery_image_border' => 'border-red-300',
            'gallery_view_link' => 'text-red-600 hover:text-red-800',
            'sidebar_header' => 'bg-red-800',
            'section_underline' => 'bg-red-600',
            'accent_badge' => 'bg-red-600',
            'media_card_hover' => 'border-2 border-gray-100 hover:border-red-400',
        ],
        [
            'border' => 'border-pink-500',
            'hover_bg' => 'hover:bg-pink-500',
            'hover_border' => 'hover:border-pink-50',
            'title_hover' => 'hover:text-pink-600',
            'read_more' => 'text-pink-600 border-pink-600 hover:bg-pink-600 hover:text-white group-hover:text-white group-hover:border-white group-hover:bg-transparent',
            'donate' => 'bg-pink-600 hover:bg-pink-700',
            'sidebar_row' => 'hover:bg-pink-50 border-gray-200 hover:border-pink-300',
            'sidebar_title' => 'group-hover:text-pink-600',
            'sidebar_link' => 'text-pink-600 group-hover:text-pink-700',
            'project_card_body' => 'group-hover:bg-pink-500',
            'gallery_image_border' => 'border-pink-300',
            'gallery_view_link' => 'text-pink-600 hover:text-pink-800',
            'sidebar_header' => 'bg-pink-800',
            'section_underline' => 'bg-pink-600',
            'accent_badge' => 'bg-pink-600',
            'media_card_hover' => 'border-2 border-gray-100 hover:border-pink-400',
        ],
        [
            'border' => 'border-yellow-500',
            'hover_bg' => 'hover:bg-yellow-500',
            'hover_border' => 'hover:border-yellow-50',
            'title_hover' => 'hover:text-yellow-600',
            'read_more' => 'text-yellow-600 border-yellow-600 hover:bg-yellow-600 hover:text-white group-hover:text-white group-hover:border-white group-hover:bg-transparent',
            'donate' => 'bg-yellow-600 hover:bg-yellow-700',
            'sidebar_row' => 'hover:bg-yellow-50 border-gray-200 hover:border-yellow-300',
            'sidebar_title' => 'group-hover:text-yellow-600',
            'sidebar_link' => 'text-yellow-600 group-hover:text-yellow-700',
            'project_card_body' => 'group-hover:bg-yellow-500',
            'gallery_image_border' => 'border-yellow-300',
            'gallery_view_link' => 'text-yellow-600 hover:text-yellow-800',
            'sidebar_header' => 'bg-yellow-700',
            'section_underline' => 'bg-yellow-600',
            'accent_badge' => 'bg-yellow-600',
            'media_card_hover' => 'border-2 border-gray-100 hover:border-yellow-400',
        ],
        [
            'border' => 'border-purple-500',
            'hover_bg' => 'hover:bg-purple-500',
            'hover_border' => 'hover:border-purple-50',
            'title_hover' => 'hover:text-purple-600',
            'read_more' => 'text-purple-600 border-purple-600 hover:bg-purple-600 hover:text-white group-hover:text-white group-hover:border-white group-hover:bg-transparent',
            'donate' => 'bg-purple-600 hover:bg-purple-700',
            'sidebar_row' => 'hover:bg-purple-50 border-gray-200 hover:border-purple-300',
            'sidebar_title' => 'group-hover:text-purple-600',
            'sidebar_link' => 'text-purple-600 group-hover:text-purple-700',
            'project_card_body' => 'group-hover:bg-purple-500',
            'gallery_image_border' => 'border-purple-300',
            'gallery_view_link' => 'text-purple-600 hover:text-purple-800',
            'sidebar_header' => 'bg-purple-800',
            'section_underline' => 'bg-purple-600',
            'accent_badge' => 'bg-purple-600',
            'media_card_hover' => 'border-2 border-gray-100 hover:border-purple-400',
        ],
        [
            'border' => 'border-indigo-500',
            'hover_bg' => 'hover:bg-indigo-500',
            'hover_border' => 'hover:border-indigo-50',
            'title_hover' => 'hover:text-indigo-600',
            'read_more' => 'text-indigo-600 border-indigo-600 hover:bg-indigo-600 hover:text-white group-hover:text-white group-hover:border-white group-hover:bg-transparent',
            'donate' => 'bg-indigo-600 hover:bg-indigo-700',
            'sidebar_row' => 'hover:bg-indigo-50 border-gray-200 hover:border-indigo-300',
            'sidebar_title' => 'group-hover:text-indigo-600',
            'sidebar_link' => 'text-indigo-600 group-hover:text-indigo-700',
            'project_card_body' => 'group-hover:bg-indigo-500',
            'gallery_image_border' => 'border-indigo-300',
            'gallery_view_link' => 'text-indigo-600 hover:text-indigo-800',
            'sidebar_header' => 'bg-indigo-800',
            'section_underline' => 'bg-indigo-600',
            'accent_badge' => 'bg-indigo-600',
            'media_card_hover' => 'border-2 border-gray-100 hover:border-indigo-400',
        ],
        [
            'border' => 'border-teal-500',
            'hover_bg' => 'hover:bg-teal-500',
            'hover_border' => 'hover:border-teal-50',
            'title_hover' => 'hover:text-teal-600',
            'read_more' => 'text-teal-600 border-teal-600 hover:bg-teal-600 hover:text-white group-hover:text-white group-hover:border-white group-hover:bg-transparent',
            'donate' => 'bg-teal-600 hover:bg-teal-700',
            'sidebar_row' => 'hover:bg-teal-50 border-gray-200 hover:border-teal-300',
            'sidebar_title' => 'group-hover:text-teal-600',
            'sidebar_link' => 'text-teal-600 group-hover:text-teal-700',
            'project_card_body' => 'group-hover:bg-teal-500',
            'gallery_image_border' => 'border-teal-300',
            'gallery_view_link' => 'text-teal-600 hover:text-teal-800',
            'sidebar_header' => 'bg-teal-800',
            'section_underline' => 'bg-teal-600',
            'accent_badge' => 'bg-teal-600',
            'media_card_hover' => 'border-2 border-gray-100 hover:border-teal-400',
        ],
        [
            'border' => 'border-orange-500',
            'hover_bg' => 'hover:bg-orange-500',
            'hover_border' => 'hover:border-orange-50',
            'title_hover' => 'hover:text-orange-600',
            'read_more' => 'text-orange-600 border-orange-600 hover:bg-orange-600 hover:text-white group-hover:text-white group-hover:border-white group-hover:bg-transparent',
            'donate' => 'bg-orange-600 hover:bg-orange-700',
            'sidebar_row' => 'hover:bg-orange-50 border-gray-200 hover:border-orange-300',
            'sidebar_title' => 'group-hover:text-orange-600',
            'sidebar_link' => 'text-orange-600 group-hover:text-orange-700',
            'project_card_body' => 'group-hover:bg-orange-500',
            'gallery_image_border' => 'border-orange-300',
            'gallery_view_link' => 'text-orange-600 hover:text-orange-800',
            'sidebar_header' => 'bg-orange-800',
            'section_underline' => 'bg-orange-600',
            'accent_badge' => 'bg-orange-600',
            'media_card_hover' => 'border-2 border-gray-100 hover:border-orange-400',
        ],
        [
            'border' => 'border-cyan-500',
            'hover_bg' => 'hover:bg-cyan-500',
            'hover_border' => 'hover:border-cyan-50',
            'title_hover' => 'hover:text-cyan-600',
            'read_more' => 'text-cyan-600 border-cyan-600 hover:bg-cyan-600 hover:text-white group-hover:text-white group-hover:border-white group-hover:bg-transparent',
            'donate' => 'bg-cyan-600 hover:bg-cyan-700',
            'sidebar_row' => 'hover:bg-cyan-50 border-gray-200 hover:border-cyan-300',
            'sidebar_title' => 'group-hover:text-cyan-600',
            'sidebar_link' => 'text-cyan-600 group-hover:text-cyan-700',
            'project_card_body' => 'group-hover:bg-cyan-500',
            'gallery_image_border' => 'border-cyan-300',
            'gallery_view_link' => 'text-cyan-600 hover:text-cyan-800',
            'sidebar_header' => 'bg-cyan-800',
            'section_underline' => 'bg-cyan-600',
            'accent_badge' => 'bg-cyan-600',
            'media_card_hover' => 'border-2 border-gray-100 hover:border-cyan-400',
        ],
    ],
];
